### PR TITLE
Add a new idea leveraging embedded reviews and nearest neighbors 

### PR DESCRIPTION
**Pull request by LeoLaugier**
Notebook with 'training' and evaluation of the multi sentence representations for RS method that Lucas and Leo work on, along with baselines

### CODE REVIEW

**Comment by iislucas** [comment]
Hi Leo, 
quick check: are all the commits by you? Seems like then github bot thinks you maybe used two different accoubts. Can you check?
@LeoLaugier

**Comment by LeoLaugier** [comment]
Hi @iislucas ,

Yes I confirm all the commits are from me. I think I had to add an email address setting for the bot to pass the agreements.

**Comment by iislucas** [comment]
OK, I had quick a look over; this is a rather huge iPython notebook with quite a bit of code that I think might be useful/reusable if put into separate files; I suggest spending a day or two organising this work so that you can re-use the parts you want to, and so that it's easier to code review by putting the libraries into dot-py files, and maybe even separating the python notebook into more meaningful parts. 

Given that these are sentence embedding-based techniques that use only a user's sentence representations; I think it's probably worth have a data-preprocessing/sampling library, and saving the intermediate data (e.g. to a pickle) so that you can continue on from that small data file without having to process the huge dataset.

Something I like a lot about this work is that it sets us up to look at the space sentence representations for a user; something that has been rather opaque for the KG recommender explorations we've done.

**Comment by LeoLaugier** [comment]
Thank you @iislucas , sure, I'm using the same code for different approaches, so I will refractor it in different Python files so that they are easily re-usable for (quick) experiments!

**Pull request merged**
